name: Build & Upload Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Grant executable permission to gradlew
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Upload all build artifacts (JAR, AAR, APK, SO)
        uses: actions/upload-artifact@v4
        with:
          name: all-build-artifacts
          path: |
            **/build/**/*.jar
            **/build/**/*.aar
            **/build/**/*.apk
            **/build/**/*.so
